@endpoint = https://pkdsi3x2le.execute-api.us-east-1.amazonaws.com/prod
GET {{endpoint}}/hello
###

GET {{endpoint}}/spaces?spaceId=1706d865-d332-451f-8980-0ce65c4a94af
###

GET {{endpoint}}/spaces?location=London
###

POST {{endpoint}}/spaces
Content-Type: application/json

{
    "location": "Londonzz",
    "name": "Best locationzzz" 
}
###