@endpoint = https://pkdsi3x2le.execute-api.us-east-1.amazonaws.com/prod
GET {{endpoint}}/hello
###

POST {{endpoint}}/spaces
Content-Type: application/json

{
    "location": "London",
    "name": "Best location" 
}
###